server:
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ums
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL.Dialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

amazon:
  access:
    key: accessKey
    secret: secretKey
    dynamodb:
        endpoint: http://localhost:8000
        region: us-east-1

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 864000000 # 10 day
      refresh-token:
        expiration: 604800000 # 7 days
