server:
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ums
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL.Dialect
          format_sql: true
